### ISSUE TITLE
屏蔽文档树图标点击事件增强

### ISSUE THREAD

**Issue by TinkMingKing** [OpaqueGlass/syplugin-doubleClickFileTree#13]
可否支持屏蔽文档树图标点击事件后同时屏蔽图标的悬浮高亮和悬浮提示？
![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/32903588/504d20ea-c250-4c7b-a768-6e8624d366b7)

**Comment by OpaqueGlass** [comment]
done，以后在集市更新。

**Comment by OpaqueGlass** [comment]
感谢反馈，稍后在集市更新。
