### ISSUE TITLE
开启插件后文档树多选功能失效

### ISSUE THREAD

**Issue by hqweay** [OpaqueGlass/syplugin-doubleClickFileTree#14]
感谢🙏作者的插件。

使用快捷键（Mac 上是 ⌘+Click）点击文档树上的文档可以多选。启动该插件后该功能失效，取消后生效。在我这稳定复现。其他朋友可以帮忙瞧瞧，不能复现我再提供下细节。

**Comment by hqweay** [comment]
> 这个功能在windows上是正常的；我并没有mac，所以难以发现和确认，麻烦尝试下面的版本。
> 
> [syplugin-doubleClickFileTree-test.zip](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/files/14891929/syplugin-doubleClickFileTree-test.zip)
> 
> （下图为windows） ![windows上未复现说明](https://private-user-images.githubusercontent.com/52985952/320168653-da10b29d-6c7e-4230-81bf-56f5a171f708.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzkyMDQsIm5iZiI6MTcxMjM3ODkwNCwicGF0aCI6Ii81Mjk4NTk1Mi8zMjAxNjg2NTMtZGExMGIyOWQtNmM3ZS00MjMwLTgxYmYtNTZmNWExNzFmNzA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA0NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDdmMGUyOTFhMWMxNmMyNzM1OGY0NDQ4ZjU0YzBjMTIyZmQ3MDQ4Y2MxM2ExZDU5NGI4MGY5OWE4ZDczZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUES2E5OYcSRMFO10NNIQZc5M8sH9w-b-1KOamL3KWk) [ ![windows上未复现说明](https://private-user-images.githubusercontent.com/52985952/320168653-da10b29d-6c7e-4230-81bf-56f5a171f708.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzkyMDQsIm5iZiI6MTcxMjM3ODkwNCwicGF0aCI6Ii81Mjk4NTk1Mi8zMjAxNjg2NTMtZGExMGIyOWQtNmM3ZS00MjMwLTgxYmYtNTZmNWExNzFmNzA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA0NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDdmMGUyOTFhMWMxNmMyNzM1OGY0NDQ4ZjU0YzBjMTIyZmQ3MDQ4Y2MxM2ExZDU5NGI4MGY5OWE4ZDczZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUES2E5OYcSRMFO10NNIQZc5M8sH9w-b-1KOamL3KWk) ](https://private-user-images.githubusercontent.com/52985952/320168653-da10b29d-6c7e-4230-81bf-56f5a171f708.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzkyMDQsIm5iZiI6MTcxMjM3ODkwNCwicGF0aCI6Ii81Mjk4NTk1Mi8zMjAxNjg2NTMtZGExMGIyOWQtNmM3ZS00MjMwLTgxYmYtNTZmNWExNzFmNzA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA0NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDdmMGUyOTFhMWMxNmMyNzM1OGY0NDQ4ZjU0YzBjMTIyZmQ3MDQ4Y2MxM2ExZDU5NGI4MGY5OWE4ZDczZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUES2E5OYcSRMFO10NNIQZc5M8sH9w-b-1KOamL3KWk) [ ](https://private-user-images.githubusercontent.com/52985952/320168653-da10b29d-6c7e-4230-81bf-56f5a171f708.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzkyMDQsIm5iZiI6MTcxMjM3ODkwNCwicGF0aCI6Ii81Mjk4NTk1Mi8zMjAxNjg2NTMtZGExMGIyOWQtNmM3ZS00MjMwLTgxYmYtNTZmNWExNzFmNzA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA0NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDdmMGUyOTFhMWMxNmMyNzM1OGY0NDQ4ZjU0YzBjMTIyZmQ3MDQ4Y2MxM2ExZDU5NGI4MGY5OWE4ZDczZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUES2E5OYcSRMFO10NNIQZc5M8sH9w-b-1KOamL3KWk)

感谢 OpaqueGlass，这个版本正常。

**Comment by OpaqueGlass** [comment]
ok，感谢反馈，稍后在集市更新。
