### ISSUE TITLE
双击笔记本

### ISSUE THREAD

**Issue by TinkMingKing** [OpaqueGlass/syplugin-doubleClickFileTree#15]
0.3.1

**Comment by OpaqueGlass** [comment]
暂未复现，请提供具体失效的功能、正在使用的思源版本以及插件设置页截图。

**Comment by TinkMingKing** [comment]
看错了，只对文档生效，不对笔记本生效

**Comment by OpaqueGlass** [comment]
确实如此，之前好像是遇到了一些问题，没有处理笔记本的双击；
此外，笔记本图标只能在文档树改，所以也没有禁用笔记本的图标切换；

**Comment by OpaqueGlass** [comment]
下个版本会屏蔽笔记本的双击，避免收起，保证一致性；感谢反馈。
