### ISSUE TITLE
双击数据库资源列导致界面卡死

### ISSUE THREAD

**Issue by TCOTC** [OpaqueGlass/syplugin-doubleClickFileTree#18]
使用该文档：[双击文档测试.sy.zip](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/files/15175429/sy.zip)

插件设置：

![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/78434827/7aaeaf4b-a937-4ddc-b400-18af220f96bf)

演示：

![插件](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/78434827/d6570821-140f-44b4-a894-27a83f23a901)

**Comment by OpaqueGlass** [comment]
未能复现，麻烦检查我下面的尝试是否有所不同

![复现尝试1](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/52985952/814afb28-97bd-429c-9c08-727017a8a3ca)

**Comment by TCOTC** [comment]
我试了一下小的数据库不容易复现，只有很大的数据库才容易复现，我怀疑这个还跟电脑性能有关

**Comment by TCOTC** [comment]
好家伙，刚刚更新 v3.0.13-dev1 后不开插件也能复现了，怀疑是思源的问题了

**Comment by TCOTC** [comment]
这个 issue 的问题应该与插件无关，先关闭了
