### ISSUE TITLE
希望标签树也在双击插件的作用范围

### ISSUE THREAD

**Issue by moonxorsun** [OpaqueGlass/syplugin-doubleClickFileTree#19]
如题，希望可以做成标签树和文档树都可以单击展开，感谢作者~

**Comment by OpaqueGlass** [comment]
我没理解错的话，设置中应该有设置项了（标签面板也一样），打开就行。
实验性功能，遇到bug麻烦反馈。

**Comment by moonxorsun** [comment]
> 我没理解错的话，设置中应该有设置项了（标签面板也一样），打开就行。 实验性功能，遇到bug麻烦反馈。

确实可以，感谢回复
