### ISSUE TITLE
打开文档时展开/收起子节点 设置项更改，允许不收起

### ISSUE THREAD

**Issue by jim555666888** [OpaqueGlass/syplugin-doubleClickFileTree#23]
<img width="1006" alt="image" src="https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/105782402/9ad54e9d-154b-497d-b769-90a0e4099837">

如题，希望能做成：

单击节点：能查看当前笔记以及展开子节点。如果再次单击节点，不希望它收起子节点。目前每次点击文档都会循环收起、展开，和原生的体验不一致。或者可以加一个选项，把收起和展开当做2个不同的选项。望采纳，跪谢！！！

**Comment by OpaqueGlass** [comment]
嗯...“原生的体验”？这个功能原本有吗

**Comment by jim555666888** [comment]
> 哪里难搞了。实现的话再等

我说的原生是指他们反复点击笔记的节点，并不会收回子节点（当然也不会展开）。

我个人使用的体验时候，**有时经常点到已展开的笔记节点，但并不是为了收起子节点，而纯粹就是为了再浏览该笔记而已**。

我估计难搞可能是思源的api的问题的吧，但我有个建议，如果点击时判断这个节点是展开的，那么就是把当前点击事件引入黑洞，不响应它，这样是不是就可以？（但不影响点击箭头仍然能收起/展开子节点）

**Comment by OpaqueGlass** [comment]
> 如果点击时判断这个节点是展开的，那么就是把当前点击事件引入黑洞，不响应它，这样是不是就可以？（但不影响点击箭头仍然能收起/展开子节点）

看了一下，应该可以，感谢反馈。

**Comment by jim555666888** [comment]
> > 如果点击时判断这个节点是展开的，那么就是把当前点击事件引入黑洞，不响应它，这样是不是就可以？（但不影响点击箭头仍然能收起/展开子节点）
> 
> 看了一下，应该可以，感谢反馈。

期待更新，谢谢😄😄😄

**Comment by OpaqueGlass** [comment]
测试版下载：https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/releases/tag/v0.3.4-beta1

> 
> ![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/52985952/3fc42e45-483a-4ed8-b7ee-579835f1d207)

**Comment by jim555666888** [comment]
<img width="441" alt="image" src="https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/105782402/57b05983-6ddd-4526-9a73-7c82d9dff925">

非常完美，爱了爱了~~
