### ISSUE TITLE
bug，此插件与“更换emoji”的冲突

### ISSUE THREAD

**Issue by luluciamk** [OpaqueGlass/syplugin-doubleClickFileTree#26]
大大，最近发现一个bug。
即，开启这个插件后，点击文档emoji图标就失去响应——在插件设置里，并没有打开“禁用emoji切换”这个选项。
平常还经常需要更换emoji，应该不是其他插件引起的冲突（关闭这个插件后就又可以更换emoji）
so，看到的话请修正一下🎃。

**Comment by luluciamk** [comment]
补充说明。
这个bug的奇怪点是——
如果一个文档的emoji是原生文档式样（没有修改过），那点击后还可以更改emoji
如果这个文档的emoji曾经被改过，再点击这个emoji，就无法更改。

**Comment by OpaqueGlass** [comment]
感谢反馈，已经初步确认问题，下个版本修复；

另外确认一下：是只有“自定义”的emoji（通过导入svg、png等图片的）有这个问题，而😅等系统自带emoji没有，对吧？

**Comment by luluciamk** [comment]
是的，经大大提醒去测试了一下，就是外部导入的图标，更换后就无法再度操作，原生的倒是没问题。

**Comment by OpaqueGlass** [comment]
已经可以在集市下载更新，感谢反馈。我先关闭issue了，如果还有问题可继续回复。
