### ISSUE TITLE
希望能够实现移动文档时的弹窗中，单击显示子文档逻辑

### ISSUE THREAD

**Issue by MisakaImouto8912** [OpaqueGlass/syplugin-doubleClickFileTree#4]
![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/47753140/6b430bfd-3bc3-498e-b858-06a4f9876d21)

**Comment by OpaqueGlass** [comment]
最新的代码已经加入了，项目主页绿色的Code按钮，下载zip，然后插件设置里有选项；这个单双击处理总感觉很奇怪，而且也挺卡，你可以试试，我大概不会加入正式更新中。

**Comment by MisakaImouto8912** [comment]
非常感谢，个人感觉没有啥卡顿，跟文档树的延迟没有区别。

**Comment by OpaqueGlass** [comment]
对应功能已经发布，此issue将被关闭。（如果没有发现bug，不必回复）
