### ISSUE TITLE
能够在移动端使用

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-doubleClickFileTree#5]
相较于电脑端，

移动端因为本身操作面积小

因此更需要这个插件

希望早日适配移动端

**Comment by OpaqueGlass** [comment]
最新的代码已经加入了，项目主页绿色的Code按钮，下载zip，然后插件设置里有选项；

对对话框中的文档树形列表做单双击处理总感觉很奇怪，而且也挺卡，你可以试试。

**Comment by QQQOrange** [comment]
> 最新的代码已经加入了，项目主页绿色的Code按钮，下载zip，然后插件设置里有选项；
> 
> 对对话框中的文档树形列表做单双击处理总感觉很奇怪，而且也挺卡，你可以试试，我大概不会加入正式更新中。

好呀好呀

**Comment by QQQOrange** [comment]
> 最新的代码已经加入了，项目主页绿色的Code按钮，下载zip，然后插件设置里有选项；
> 
> 对对话框中的文档树形列表做单双击处理总感觉很奇怪，而且也挺卡，你可以试试，我大概不会加入正式更新中。

刚刚用了一下，在文档筛选页面用，很舒适啊，可以留着啊，安卓的有 bug，但是关闭插件后发现还有，那应该是思源本身的问题

**Comment by OpaqueGlass** [comment]
安卓的有什么bug？关闭插件后最好还是重启一下思源，有可能是插件没卸载掉

双击选择的逻辑有点怪，而且不太适合多选

**Comment by QQQOrange** [comment]
> 安卓的有什么bug？关闭插件后最好还是重启一下思源，有可能是插件没卸载掉
> 
> 双击选择的逻辑有点怪，而且不太适合多选

在思源闪卡文档树页面，一进去，它会弹出输入法，你把输入法点掉之后，你每.1次文档输入，它都会弹一次。不过这个是思源的问题

**Comment by QQQOrange** [comment]
> 安卓的有什么bug？关闭插件后最好还是重启一下思源，有可能是插件没卸载掉
> 
> 双击选择的逻辑有点怪，而且不太适合多选

设置多选的时候插件失效可以吗

**Comment by OpaqueGlass** [comment]
> 在思源闪卡文档树页面，一进去，它会弹出输入法，你把输入法点掉之后，你每.1次文档输入，它都会弹一次。不过这个是思源的问题
我这插件关了之后就没这个问题了，我再看看啥情况；

> 设置多选的时候插件失效可以吗
现在是判断的桌面端的逻辑，桌面端多选需要按ctrl，插件在ctrl按下时不处理，手机端没做

**Comment by QQQOrange** [comment]
> > 在思源闪卡文档树页面，一进去，它会弹出输入法，你把输入法点掉之后，你每.1次文档输入，它都会弹一次。不过这个是思源的问题
> 
> 我这插件关了之后就没这个问题了，我再看看啥情况；
> 
> 哦，我这里是保持输入法存在的，插件开启的情况下点击后输入法会闪（消失然后重新出现）；不开插件的话还好，输入法会一直在那儿，也不太影响；还不太确定问题出在哪
> 
> > 设置多选的时候插件失效可以吗
> 
> 现在是只处理了桌面端，桌面端多选需要按ctrl，插件在ctrl按下时不处理，手机端没做

手机端应该还好，不对，安卓端有平板，那说不定也需要

**Comment by QQQOrange** [comment]
> > 在思源闪卡文档树页面，一进去，它会弹出输入法，你把输入法点掉之后，你每.1次文档输入，它都会弹一次。不过这个是思源的问题
> 
> 我这插件关了之后就没这个问题了，我再看看啥情况；
> 
> 哦，我这里是保持输入法存在的，插件开启的情况下点击后输入法会闪（消失然后重新出现）；不开插件的话还好，输入法会一直在那儿，也不太影响；还不太确定问题出在哪
> 
> > 设置多选的时候插件失效可以吗
> 
> 现在是只处理了桌面端，桌面端多选需要按ctrl，插件在ctrl按下时不处理，手机端没做

问题是思源本身的，不是你这个插件的

**Comment by OpaqueGlass** [comment]
> 手机端应该还好，不对，安卓端有平板，那说不定也需要

我还不知道手机端要怎么多选；平板端目前实际上用的桌面端的布局，那应该也是Ctrl+点击多选，这个不影响，插件应该已经避开了；

**Comment by QQQOrange** [comment]
> > 手机端应该还好，不对，安卓端有平板，那说不定也需要
> 
> 我还不知道手机端要怎么多选；平板端目前实际上用的桌面端的布局，那应该也是Ctrl+点击多选，这个不影响，插件应该已经避开了；

哦哦哦

**Comment by OpaqueGlass** [comment]
对应功能已经发布，此issue将被关闭。（如果没有发现bug，不必回复）
