### ISSUE TITLE
能够在闪卡复习页面的文档树筛选中使用

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-doubleClickFileTree#6]
![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/62794181/536d0b7a-ce00-40b0-b3e0-5595c1a858a2)
![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/62794181/68294e83-6204-4133-9030-7a701350c11a)
也既是此页面

**Comment by OpaqueGlass** [comment]
对应功能已经发布，此issue将被关闭。（如果没有发现bug，不必回复）
