### ISSUE TITLE
设置单击打开子文档，但在大纲视图中双击也产生此操作

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-doubleClickFileTree#7]
https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/62794181/477bec08-54a9-4d93-b6a5-ac402a29e8eb

设定的是单击打开子文档，双击打开文档

但是双击也会展开打开子文档

**Comment by OpaqueGlass** [comment]
感谢反馈，如果可以，麻烦补充以下信息：
别关思源，代码片段在JS加一下下面的内容、并启用，Ctrl+Shift+I，切换到控制台/Console，重新操作一下，像下图加一下筛选，发个截图，谢谢。
![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/52985952/76e41dfc-59ce-46f8-9d3a-a2dd2f3a26b1)

```js
(function(){
window.top["OpaqueGlassDebug"] = true;
window.top["OpaqueGlassDebugV2"] ={
     "none": 1
    //,"lcd": 5
   , "fte": 5
  //  ,"hn": 5
   // ,"fdb": 5
  //  ,"tw": 5
   //, "replaceImage": 5
  // , "temp": 5
}
})();
```

**Comment by OpaqueGlass** [comment]
![image](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/52985952/9f71366c-1c19-414c-bbca-1d38c73d27f0)
是因为开启了这个

**Comment by QQQOrange** [comment]
> ![image](https://private-user-images.githubusercontent.com/52985952/307503228-9f71366c-1c19-414c-bbca-1d38c73d27f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTk3MTYsIm5iZiI6MTcwODc1OTQxNiwicGF0aCI6Ii81Mjk4NTk1Mi8zMDc1MDMyMjgtOWY3MTM2NmMtMWMxOS00MTRjLWJiY2EtMWQzOGM3M2QyN2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNDc1NmU3MGExNWJmMGQ5OTg4MjgzZTc2NjQzYWIxZDc5NWNmZTA3ODljZjM3ODg3MjQ5NDBlYzk3ZmI3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4QCQ7xEKXvswBeqOJXmP7aFFSYBRVNh_uNHF2m-E5p4) 是因为开启了这个

好家伙，抱歉，是我没注意

**Comment by OpaqueGlass** [comment]
之后我改一下这个设置项的名字/注解，先关了哈。
