### ISSUE TITLE
隐藏文档树图标等功能

### ISSUE THREAD

**Issue by tongzi001** [OpaqueGlass/syplugin-doubleClickFileTree#8]
感谢作者提供久违的功能~！能否考虑以下功能：
1.隐藏文档树前的图标；
2.可设置取消文档树的缩进，自定义颜色区分父子目录；
3.文档树独立窗口，文档树层级增多时目录太靠右了，拖来拖去十分不便;
4.文档树字体大小调整；
5.文档树上下间距调整。

**Comment by OpaqueGlass** [comment]
抱歉，我不会css样式相关的调整，这个插件仅仅对左键单击、双击的行为做更改；此issue将被关闭，感谢反馈。

有位大佬写的文档树自定义插件包含了 1）4）5）功能，可以去这里了解：https://ld246.com/article/1705227991331

关于3）新建窗口显示文档树，这可能需要插件在一个全新的页面自己实现一个文档树，新窗口和笔记主窗口之间可能还需要另外的消息通信，我没有这个能力和精力去完成；
关于2）调整外观样式涉及的东西太多，还存在相互制约；此外，思源每次展开都是重写的结构，自定义颜色需要插件监视并对每次展开都做出响应；
关于1）也可以使用代码片段：
```css
.sy__file .b3-list-item__icon{
display:none;
}
```

**Comment by tongzi001** [comment]
好的谢谢。那位大佬的文档树插件已经作废了，没法拿出来了。

**Comment by OpaqueGlass** [comment]
误封应该还能解吧🙏
